Re implement tests

diff --git a/.github/workflows/fdp_cpp_api.yaml b/.github/workflows/fdp_cpp_api.yaml
--- a/.github/workflows/fdp_cpp_api.yaml
+++ b/.github/workflows/fdp_cpp_api.yaml
@@ -19,6 +19,23 @@ jobs:
           cmake -Bbuild -DFDPAPI_BUILD_TESTS=ON
       - name: Compile FDP-Cpp-API
         run: cmake --build build
+      - name: Run Unit Tests
+       run: |
+         bash test/test_setup.sh
+         cmake --build build --target test
+         if [ $? -eq 0 ]; then
+           echo "Unit tests completed successfully"
+           exit 0
+         else
+           echo "Unit tests failed"
+           exit 1
+         fi
+      - name: SonarCloud Scan
+        run: |
+          sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -X
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   Build_MacOS:
     name: Build MacOS
     runs-on: macOS-latest
